- id: log_weather_forecast
  alias: Log Weather Forecast
  trigger:
  - platform: time
    at: 08:00:00
  action:
  - service: system_log.write
    data:
      message: '{{ state_attr(''weather.met_no_next_6_hours_forecast_home'', ''forecast_json'')
        }}

        '
- id: '1728223142621'
  alias: Set thermostats
  description: Set thermostat based on 3 block such as Evaluate room conditions, Evaluate
    financial situation and Actions
  trigger: []
  condition: []
  action: []
  mode: restart
- id: '1728224929925'
  alias: Set thermostats
  description: Set thermostat based on 3 block such as Evaluate room conditions, Evaluate
    financial situation and Actions
  trigger:
  - platform: time_pattern
    minutes: 0
  condition: []
  action: []
  mode: restart
- id: '1728224942436'
  alias: Set thermostats
  description: Set thermostat based on 3 block such as Evaluate room conditions, Evaluate
    financial situation and Actions
  trigger:
  - platform: time_pattern
    minutes: 0
  condition: []
  action: []
  mode: restart
