- id: log_weather_forecast
  alias: Log Weather Forecast
  trigger:
  - platform: time
    at: 08:00:00
  action:
  - service: system_log.write
    data:
      message: '{{ state_attr(''weather.met_no_next_6_hours_forecast_home'', ''forecast_json'')
        }}

        '
- id: '1728223142621'
  alias: Set thermostats
  description: Set thermostat based on 3 block such as Evaluate room conditions, Evaluate
    financial situation and Actions
  trigger: []
  condition: []
  action: []
  mode: restart
- id: '1728224929925'
  alias: Set thermostats
  description: Set thermostat based on 3 block such as Evaluate room conditions, Evaluate
    financial situation and Actions
  trigger:
  - platform: time_pattern
    minutes: 0
  condition: []
  action: []
  mode: restart
- id: '1728224942436'
  alias: Set thermostats
  description: Set thermostat based on 3 block such as Evaluate room conditions, Evaluate
    financial situation and Actions
  trigger:
  - platform: time_pattern
    minutes: 0
  condition: []
  action: []
  mode: restart
- id: '1728300544744'
  alias: Control comfort settings
  description: ''
  use_blueprint:
    path: homeassistant/heating/comfort_settings.yaml
    input:
      min_temperature: input_number.entrance_min_temperature
      max_temperature: input_number.entrance_max_temperature
      target_temperature: input_number.entrance_target_temperature
- id: '1728301851705'
  alias: Control comfort settings
  description: ''
  use_blueprint:
    path: homeassistant/heating/comfort_settings.yaml
    input:
      min_temperature: input_number.entrance_min_temperature
      max_temperature: input_number.entrance_max_temperature
      target_temperature: input_number.entrance_target_temperature
- id: '1728302124793'
  alias: Control comfort settings
  description: ''
  use_blueprint:
    path: homeassistant/heating/comfort_settings.yaml
    input:
      min_temperature: input_number.entrance_min_temperature
      max_temperature: input_number.entrance_max_temperature
      target_temperature: input_number.entrance_target_temperature
