- id: log_weather_forecast
  alias: Log Weather Forecast
  trigger:
  - platform: time
    at: 08:00:00
  action:
  - service: system_log.write
    data:
      message: '{{ state_attr(''weather.met_no_next_6_hours_forecast_home'', ''forecast_json'')
        }}

        '
- id: '1728223142621'
  alias: Set thermostats
  description: Set thermostat based on 3 block such as Evaluate room conditions, Evaluate
    financial situation and Actions
  trigger: []
  condition: []
  action: []
  mode: restart
- id: '1728224929925'
  alias: Set thermostats
  description: Set thermostat based on 3 block such as Evaluate room conditions, Evaluate
    financial situation and Actions
  trigger:
  - platform: time_pattern
    minutes: 0
  condition: []
  action: []
  mode: restart
- id: '1728224942436'
  alias: Set thermostats
  description: Set thermostat based on 3 block such as Evaluate room conditions, Evaluate
    financial situation and Actions
  trigger:
  - platform: time_pattern
    minutes: 0
  condition: []
  action: []
  mode: restart
- id: '1728300544744'
  alias: Control comfort settings
  description: ''
  use_blueprint:
    path: homeassistant/heating/comfort_settings.yaml
    input:
      min_temperature: input_number.entrance_min_temperature
      max_temperature: input_number.entrance_max_temperature
      target_temperature: input_number.entrance_target_temperature
- id: '1728301851705'
  alias: Control comfort settings
  description: ''
  use_blueprint:
    path: homeassistant/heating/comfort_settings.yaml
    input:
      min_temperature: input_number.entrance_min_temperature
      max_temperature: input_number.entrance_max_temperature
      target_temperature: input_number.entrance_target_temperature
- id: '1728302124793'
  alias: Control comfort settings
  description: ''
  use_blueprint:
    path: homeassistant/heating/comfort_settings.yaml
    input:
      min_temperature: input_number.entrance_min_temperature
      max_temperature: input_number.entrance_max_temperature
      target_temperature: input_number.entrance_target_temperature
- id: '1728302422346'
  alias: New automation
  description: ''
  use_blueprint:
    path: homeassistant/heating/comfort_settings.yaml
    input:
      min_temperature: input_number.entrance_min_temperature
      max_temperature: input_number.entrance_max_temperature
      target_temperature: input_number.entrance_target_temperature
- id: '1728302494196'
  alias: Control kitchen comfort settings
  description: Use blueprint control comfort settings
  use_blueprint:
    path: homeassistant/heating/comfort_settings.yaml
    input:
      min_temperature: input_number.kitchen_min_temperature
      max_temperature: input_number.kitchen_max_temperature
      target_temperature: input_number.kitchen_target_temperature
- id: '1728302561888'
  alias: Kitchen control comfort settings
  description: Use blueprint control comfort settings
  use_blueprint:
    path: homeassistant/heating/comfort_settings.yaml
    input:
      min_temperature: input_number.kitchen_min_temperature
      max_temperature: input_number.kitchen_max_temperature
      target_temperature: input_number.kitchen_target_temperature
- id: '1728449667286'
  alias: Evaluate room conditions
  description: ''
  use_blueprint:
    path: homeassistant/heating/room_conditions.yaml
    input:
      room_temperature: sensor.kitchen_temperature_and_humidity_sensor_temperature
      min_temperature: input_number.kitchen_min_temperature
      max_temperature: input_number.kitchen_max_temperature
      pipeline: input_text.pipeline
- id: '1728449759068'
  alias: New automation
  description: ''
  use_blueprint:
    path: homeassistant/heating/room_conditions.yaml
    input:
      room_temperature: sensor.kitchen_temperature_and_humidity_sensor_temperature
      min_temperature: input_number.kitchen_min_temperature
      max_temperature: input_number.kitchen_max_temperature
      pipeline: input_text.pipeline
- id: '1728449915942'
  alias: Evaluate room conditions - Kitchen
  description: ''
  use_blueprint:
    path: homeassistant/heating/room_conditions.yaml
    input:
      room_temperature: sensor.kitchen_temperature_and_humidity_sensor_temperature
      min_temperature: input_number.kitchen_min_temperature
      max_temperature: input_number.kitchen_max_temperature
      pipeline: input_text.pipeline
- id: '1728451065810'
  alias: Kitchen rooms conditions
  description: ''
  use_blueprint:
    path: homeassistant/heating/room_conditions.yaml
    input:
      room_temperature: sensor.kitchen_temperature_and_humidity_sensor_temperature
      min_temperature: input_number.kitchen_min_temperature
      max_temperature: input_number.kitchen_max_temperature
      pipeline: input_text.pipeline
- id: '1728452117748'
  alias: Kitchen - Rooms conditions
  description: ''
  use_blueprint:
    path: homeassistant/heating/room_conditions.yaml
    input:
      room_temperature: sensor.kitchen_temperature_and_humidity_sensor_temperature
      min_temperature: input_number.kitchen_min_temperature
      max_temperature: input_number.kitchen_max_temperature
      pipeline: input_text.pipeline
- id: '1728452153192'
  alias: New automation
  description: ''
  use_blueprint:
    path: homeassistant/heating/comfort_settings.yaml
    input:
      min_temperature: input_number.kitchen_min_temperature
      max_temperature: input_number.kitchen_max_temperature
      target_temperature: input_number.kitchen_target_temperature
- id: '1729676969576'
  alias: Kitchen blueprint test
  description: Test
  use_blueprint:
    path: homeassistant/heating/financial_conditions.yaml
    input:
      user: mobile_app_sebastians_iphone
      price_trend: input_text.price_trend
      current_year_average_price: sensor.current_year_average_price
      nordpool: sensor.nordpool_kwh_fi_eur_2_10_0255
      room_name: Makkari
      room_temperature: sensor.bedroom_temperature_and_humidity_sensor_temperature
      min_temperature: input_number.kitchen_min_temperature
      max_temperature: input_number.kitchen_max_temperature
      heating_schedule_start_time: input_datetime.kitchen_heating_schedule_start_time
      heating_schedule_end_time: input_datetime.kitchen_heating_schedule_end_time
      pipeline_settings: sensor.kitchen_pipeline
