# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include_dir_merge_list automations/

input_number: !include_dir_merge_named configurations/input_number/
input_datetime: !include_dir_merge_named configurations/input_datetime/


climate: !include configurations/climate/adax.yaml
input_boolean: !include configurations/input_boolean/alarm_system.yaml
input_text: !include  configurations/input_text/adax.yaml
rest_command: !include configurations/rest_command/adax.yaml
sensor: !include_dir_merge_list  configurations/sensor/




 

#script: !include scripts.yaml
scene: !include scenes.yaml
#secrets: !include secrets.yaml

# These lines are important for the mini-graph-card to work and apexcharts-card to work.
#resources:
#  - url: /local/mini-graph-card-bundle.js?v=0.12.1
#    type: module
#   
#  - url: /local/apexcharts-card.js?v=2.0.4
#    type: module