# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include_dir_merge_list automations/

logger:
  logs:
    custom_components.extended_openai_conversation: info


climate: !include_dir_merge_list  configurations/climate/
counter: !include_dir_merge_named  configurations/counter/
input_boolean: !include_dir_merge_named configurations/input_boolean/
input_datetime: !include_dir_merge_named configurations/input_datetime/
input_number: !include_dir_merge_named configurations/input_number/
input_text: !include_dir_merge_named configurations/input_text/
rest_command: !include_dir_merge_named configurations/rest_command/
sensor: !include_dir_merge_list  configurations/sensor/
switch: !include_dir_merge_list  configurations/switch/
script: !include_dir_merge_list scripts/weather_forecasts/ # IS THIS CORRECT?

 

#script: !include scripts.yaml
scene: !include scenes.yaml
#secrets: !include secrets.yaml

# These lines are important for the mini-graph-card to work and apexcharts-card to work.
#resources:
#  - url: /local/mini-graph-card-bundle.js?v=0.12.1
#    type: module
#   
#  - url: /local/apexcharts-card.js?v=2.0.4
#    type: module