# Name: comfort_settings.yaml
# Author: Sebastian Sopola @ https://www.linkedin.com/in/sebastiansopola/
# Description: This file containts the automations to control comfort settings in UI. Enforcing rules utilizing blueprint Control comfort settings.



- id: entrance_comfort_settings
  alias: Control entrance comfort settings
  description: Control comfort settings. Use blueprint Control comfort settings to enforce control.
  use_blueprint:
    path: homeassistant/heating/comfort_settings.yaml
    input: # no input sections needed when using blueprints
      min_temperature: input_number.entrance_min_temperature
      max_temperature: input_number.entrance_max_temperature
      target_temperature: input_number.entrance_target_temperature

- id: kitchen_comfort_settings
  alias: Control kitchen comfort settings
  description: Control comfort settings. Use blueprint Control comfort settings to enforce control.
  use_blueprint:
    path: homeassistant/heating/comfort_settings.yaml
    input:
      min_temperature: input_number.kitchen_min_temperature
      max_temperature: input_number.kitchen_max_temperature
      target_temperature: input_number.kitchen_target_temperature

- id: bedroom_comfort_settings
  alias: Control bedroom comfort settings
  description: Control comfort settings. Use blueprint Control comfort settings to enforce control.
  use_blueprint:
    path: homeassistant/heating/comfort_settings.yaml
    input:
      min_temperature: input_number.bedroom_min_temperature
      max_temperature: input_number.bedroom_max_temperature
      target_temperature: input_number.bedroom_target_temperature

- id: living_room_comfort_settings
  alias: Control living room comfort settings
  description: Control comfort settings. Use blueprint Control comfort settings to enforce control.
  use_blueprint:
    path: homeassistant/heating/comfort_settings.yaml
    input:
      min_temperature: input_number.living_room_min_temperature
      max_temperature: input_number.living_room_max_temperature
      target_temperature: input_number.living_room_target_temperature

- id: main_bedroom_comfort_settings
  alias: Control main bedroom comfort settings
  description: Control comfort settings. Use blueprint Control comfort settings to enforce control.
  use_blueprint:
    path: homeassistant/heating/comfort_settings.yaml
    input:
      min_temperature: input_number.main_bedroom_min_temperature
      max_temperature: input_number.main_bedroom_max_temperature
      target_temperature: input_number.main_bedroom_target_temperature

- id: guest_bedroom_comfort_settings
  alias: Control guest bedroom comfort settings
  description: Control comfort settings. Use blueprint Control comfort settings to enforce control.
  use_blueprint:
    path: homeassistant/heating/comfort_settings.yaml
    input:
      min_temperature: input_number.guest_bedroom_min_temperature
      max_temperature: input_number.guest_bedroom_max_temperature
      target_temperature: input_number.guest_bedroom_target_temperature