# Virtual thermostat in UI, controls physical thermostats
- platform: generic_thermostat
  unique_id: virtual_thermostat
  name: Virtual Thermostat
  heater: switch.your_heater_switch
  target_sensor: sensor.your_temperature_sensor
  min_temp: 5
  max_temp: 35
  ac_mode: false
  target_temp: 21
  precision: 1.0
  cold_tolerance: 0.5
  hot_tolerance: 0.5 
  initial_hvac_mode: "heat"
