# Name: pipeline.yaml
# Author: Sebastian Sopola @ https://www.linkedin.com/in/sebastiansopola/
# Description: This file containts the configuration for providing pipeline blocks' states.



living_room_pipeline_status:
  name: "Provide living room pipeline status entity"
  initial: true
  icon: mdi:state-machine

living_room_block_0:
  name: "Provide Block 0 state"
  initial: false
  icon: mdi:state-machine

living_room_block_1:
  name: "Provide Block 1 state"
  initial: false
  icon: mdi:state-machine

living_room_block_2_case_1:
  name: "Provide Block 2 state"
  initial: false
  icon: mdi:state-machine

living_room_block_2_case_2:
  name: "Provide Block 2 state"
  initial: false
  icon: mdi:state-machine

living_room_block_2_case_3:
  name: "Provide Block 2 state"
  initial: false
  icon: mdi:state-machine

living_room_block_3:
  name: "Provide Block 3 state"
  initial: false
  icon: mdi:state-machine

living_room_preheat_by_5:
  name: "Provide Block 3 preheat level 1"
  initial: false
  icon: mdi:state-machine

living_room_preheat_by_12:
  name: "Provide Block 3 preheat level 2"
  initial: false
  icon: mdi:state-machine

living_room_preheat_by_20:
  name: "Provide Block 3 preheat level 3"
  initial: false
  icon: mdi:state-machine

living_room_preheat_max:
  name: "Provide Block 3 preheat level 4"
  initial: false
  icon: mdi:state-machine

living_room_maintain_heat:
  name: "Provide Block 3 maintain heat boolean"
  initial: false
  icon: mdi:state-machine

living_room_delay_heat:
  name: "Provide Block 3 delay to heat boolean"
  initial: false
  icon: mdi:state-machine

living_room_block_4:
  name: "Provide Block 4 state"
  initial: false
  icon: mdi:state-machine