- platform: template
  sensors:
    coefficient:
      friendly_name: "Heat loss coefficient"
      value_template: >
        {% set month = now().month %}
        {% if month >= 5 and month <= 9 %}
          {{ 0.35 }}
        {% else %}
          {{ 0.75 }}
        {% endif %}