# Name: electric_stock_prices.yaml
# Author: Sebastian Sopola @ https://www.linkedin.com/in/sebastiansopola/
# Description: This file containts the configuration for providing nordpool integration to access electric stock market data, current year price average, etc



- platform: nordpool
  VAT: true
  currency: "EUR"
  price_in_cents: true
  region: "FI"
  precision: 2
  price_type: kWh 

- platform: template
  sensors:
    current_year_average_price:
      friendly_name: "Current year average electric stock market price" # ADD LOGIC TO ACTUALLY CALCULATE IT AT SOME POINT
      value_template: "{{10}}"

    electric_price_classification_8hr:
      friendly_name: "Classification for 8 next hours of electric stock market prices"
      value_template: >
        {
          "{{ states('input_number.hour_1') }}": {{ states('input_text.hour_1_type') }}, 
          "{{ states('input_number.hour_2') }}": {{ states('input_text.hour_2_type') }}, 
          "{{ states('input_number.hour_3') }}": {{ states('input_text.hour_3_type') }},
          "{{ states('input_number.hour_4') }}": {{ states('input_text.hour_4_type') }},
          "{{ states('input_number.hour_5') }}": {{ states('input_text.hour_5_type') }}, 
          "{{ states('input_number.hour_6') }}": {{ states('input_text.hour_6_type') }}, 
          "{{ states('input_number.hour_7') }}": {{ states('input_text.hour_7_type') }},
          "{{ states('input_number.hour_8') }}": {{ states('input_text.hour_8_type') }}
        }
        
# Use this if sorting is done in classification phase
#{
#  "hour_1": { "type": "{{ states('input_text.hour_1_type') }}", "price": "{{ states('input_number.hour_1_price') | float }}" },
#  "hour_2": { "type": "{{ states('input_text.hour_2_type') }}", "price": "{{ states('input_number.hour_2_price') | float }}" },
#  "hour_3": { "type": "{{ states('input_text.hour_3_type') }}", "price": "{{ states('input_number.hour_3_price') | float }}" },
#  "hour_4": { "type": "{{ states('input_text.hour_4_type') }}", "price": "{{ states('input_number.hour_4_price') | float }}" },
#  "hour_5": { "type": "{{ states('input_text.hour_5_type') }}", "price": "{{ states('input_number.hour_5_price') | float }}" },
#  "hour_6": { "type": "{{ states('input_text.hour_6_type') }}", "price": "{{ states('input_number.hour_6_price') | float }}" },
#  "hour_7": { "type": "{{ states('input_text.hour_7_type') }}", "price": "{{ states('input_number.hour_7_price') | float }}" },
#  "hour_8": { "type": "{{ states('input_text.hour_8_type') }}", "price": "{{ states('input_number.hour_8_price') | float }}" }
#}