# Name: electric_stock_prices.yaml
# Author: Sebastian Sopola @ https://www.linkedin.com/in/sebastiansopola/
# Description: This file containts the configuration for providing accessibility to nordpool integration providing electric stock market prices.



- platform: nordpool
  VAT: true
  currency: "EUR"
  price_in_cents: true
  region: "FI"
  precision: 2
  price_type: kWh 