# Name: coefficients.yaml
# Author: Sebastian Sopola @ https://www.linkedin.com/in/sebastiansopola/
# Description: This file containts the configuration providing heat transfer coefficient for heating calculations
# Warning: Its RECOMMENDED to use same formatting. Otherwise the program will run into errors!



- platform: template
  sensors:

    # -----------------------------------------------------------------------------------------------------------------------------------------------------
    # - This sensor provides coefficient, which is used to calculate heat loss, heat requirement, etc which allow more robust automated heating solutions -
    # -----------------------------------------------------------------------------------------------------------------------------------------------------
    heat_transfer_coefficient:
      friendly_name: "Heat transfer coefficient"
      value_template: >
        {% set month = now().month %}
        {% if month >= 5 and month <= 9 %}
          {{ 0.35 }}
        {% else %}
          {{ 0.75 }}
        {% endif %}