# Name: pipeline.yaml
# Author: Sebastian Sopola @ https://www.linkedin.com/in/sebastiansopola/
# Description: This file containts the configuration for providing pipeline logic to move onto from block to another.



- platform: template
  sensors:
    entrance_pipeline:
        friendly_name: "Heating system pipeline for entrance"
        value_template: "{{ states('input_boolean.entrance_pipeline_status') }}"
        attribute_templates:
          block_0: "{{ states('input_boolean.entrance_block_0') }}"
          block_1: "{{ states('input_boolean.entrance_block_1') }}"
          block_2_case_1: "{{ states('input_boolean.entrance_block_2_case_1') }}"
          block_2_case_2: "{{ states('input_boolean.entrance_block_2_case_2') }}"
          block_2_case_3: "{{ states('input_boolean.entrance_block_2_case_3') }}"
          block_3: >
            {
              "state": "{{ states('input_boolean.entrance_block_3') }}",
              "preheat_by_5": "{{ states('input_boolean.entrance_preheat_by_5') }}",
              "preheat_by_12": "{{ states('input_boolean.entrance_preheat_by_12') }}",
              "preheat_by_20": "{{ states('input_boolean.entrance_preheat_by_20') }}",
              "preheat_max": "{{ states('input_boolean.entrance_preheat_max') }}",
              "maintain_heat": "{{ states('input_boolean.entrance_maintain_heat') }}",
              "delay_heat": "{{ states('input_boolean.entrance_delay_heat') }}"
            }
          block_4: "{{ states('input_boolean.entrance_block_4') }}"

    kitchen_pipeline:
        friendly_name: "Heating system pipeline for kitchen"
        value_template: "{{ states('input_boolean.kitchen_pipeline_status') }}"
        attribute_templates:
          block_0: "{{ states('input_boolean.kitchen_block_0') }}"
          block_1: "{{ states('input_boolean.kitchen_block_1') }}"
          block_2_case_1: "{{ states('input_boolean.kitchen_block_2_case_1') }}"
          block_2_case_2: "{{ states('input_boolean.kitchen_block_2_case_2') }}"
          block_2_case_3: "{{ states('input_boolean.kitchen_block_2_case_3') }}"
          block_3: >
            {
              "state": "{{ states('input_boolean.kitchen_block_3') }}",
              "preheat_by_5": "{{ states('input_boolean.kitchen_preheat_by_5') }}",
              "preheat_by_12": "{{ states('input_boolean.kitchen_preheat_by_12') }}",
              "preheat_by_20": "{{ states('input_boolean.kitchen_preheat_by_20') }}",
              "preheat_max": "{{ states('input_boolean.kitchen_preheat_max') }}",
              "maintain_heat": "{{ states('input_boolean.kitchen_maintain_heat') }}",
              "delay_heat": "{{ states('input_boolean.kitchen_delay_heat') }}"
            }
          block_4: "{{ states('input_boolean.kitchen_block_4') }}"

    bedroom_pipeline:
        friendly_name: "Heating system pipeline for bedroom"
        value_template: "{{ states('input_boolean.bedroom_pipeline_status') }}"
        attribute_templates:
          block_0: "{{ states('input_boolean.bedroom_block_0') }}"
          block_1: "{{ states('input_boolean.bedroom_block_1') }}"
          block_2_case_1: "{{ states('input_boolean.bedroom_block_2_case_1') }}"
          block_2_case_2: "{{ states('input_boolean.bedroom_block_2_case_2') }}"
          block_2_case_3: "{{ states('input_boolean.bedroom_block_2_case_3') }}"
          block_3: >
            {
              "state": "{{ states('input_boolean.bedroom_block_3') }}",
              "preheat_by_5": "{{ states('input_boolean.bedroom_preheat_by_5') }}",
              "preheat_by_12": "{{ states('input_boolean.bedroom_preheat_by_12') }}",
              "preheat_by_20": "{{ states('input_boolean.bedroom_preheat_by_20') }}",
              "preheat_max": "{{ states('input_boolean.bedroom_preheat_max') }}",
              "maintain_heat": "{{ states('input_boolean.bedroom_maintain_heat') }}",
              "delay_heat": "{{ states('input_boolean.bedroom_delay_heat') }}"
            }
          block_4: "{{ states('input_boolean.bedroom_block_4') }}"

    living_room_pipeline:
        friendly_name: "Heating system pipeline for living room"
        value_template: "{{ states('input_boolean.living_room_pipeline_status') }}"
        attribute_templates:
          block_0: "{{ states('input_boolean.living_room_block_0') }}"
          block_1: "{{ states('input_boolean.living_room_block_1') }}"
          block_2_case_1: "{{ states('input_boolean.living_room_block_2_case_1') }}"
          block_2_case_2: "{{ states('input_boolean.living_room_block_2_case_2') }}"
          block_2_case_3: "{{ states('input_boolean.living_room_block_2_case_3') }}"
          block_3: >
            {
              "state": "{{ states('input_boolean.living_room_block_3') }}",
              "preheat_by_5": "{{ states('input_boolean.living_room_preheat_by_5') }}",
              "preheat_by_12": "{{ states('input_boolean.living_room_preheat_by_12') }}",
              "preheat_by_20": "{{ states('input_boolean.living_room_preheat_by_20') }}",
              "preheat_max": "{{ states('input_boolean.living_room_preheat_max') }}",
              "maintain_heat": "{{ states('input_boolean.living_room_maintain_heat') }}",
              "delay_heat": "{{ states('input_boolean.living_room_delay_heat') }}"
            }
          block_4: "{{ states('input_boolean.living_room_block_4') }}"

    main_bedroom_pipeline:
        friendly_name: "Heating system pipeline for main bedroom"
        value_template: "{{ states('input_boolean.main_bedroom_pipeline_status') }}"
        attribute_templates:
          block_0: "{{ states('input_boolean.main_bedroom_block_0') }}"
          block_1: "{{ states('input_boolean.main_bedroom_block_1') }}"
          block_2_case_1: "{{ states('input_boolean.main_bedroom_block_2_case_1') }}"
          block_2_case_2: "{{ states('input_boolean.main_bedroom_block_2_case_2') }}"
          block_2_case_3: "{{ states('input_boolean.main_bedroom_block_2_case_3') }}"
          block_3: >
            {
              "state": "{{ states('input_boolean.main_bedroom_block_3') }}",
              "preheat_by_5": "{{ states('input_boolean.main_bedroom_preheat_by_5') }}",
              "preheat_by_12": "{{ states('input_boolean.main_bedroom_preheat_by_12') }}",
              "preheat_by_20": "{{ states('input_boolean.main_bedroom_preheat_by_20') }}",
              "preheat_max": "{{ states('input_boolean.main_bedroom_preheat_max') }}",
              "maintain_heat": "{{ states('input_boolean.main_bedroom_maintain_heat') }}",
              "delay_heat": "{{ states('input_boolean.main_bedroom_delay_heat') }}"
            }
          block_4: "{{ states('input_boolean.main_bedroom_block_4') }}"

    guest_bedroom_pipeline:
        friendly_name: "Heating system pipeline for guest bedroom"
        value_template: "{{ states('input_boolean.guest_bedroom_pipeline_status') }}"
        attribute_templates:
          block_0: "{{ states('input_boolean.guest_bedroom_block_0') }}"
          block_1: "{{ states('input_boolean.guest_bedroom_block_1') }}"
          block_2_case_1: "{{ states('input_boolean.guest_bedroom_block_2_case_1') }}"
          block_2_case_2: "{{ states('input_boolean.guest_bedroom_block_2_case_2') }}"
          block_2_case_3: "{{ states('input_boolean.guest_bedroom_block_2_case_3') }}"
          block_3: >
            {
              "state": "{{ states('input_boolean.guest_bedroom_block_3') }}",
              "preheat_by_5": "{{ states('input_boolean.guest_bedroom_preheat_by_5') }}",
              "preheat_by_12": "{{ states('input_boolean.guest_bedroom_preheat_by_12') }}",
              "preheat_by_20": "{{ states('input_boolean.guest_bedroom_preheat_by_20') }}",
              "preheat_max": "{{ states('input_boolean.guest_bedroom_preheat_max') }}",
              "maintain_heat": "{{ states('input_boolean.guest_bedroom_maintain_heat') }}",
              "delay_heat": "{{ states('input_boolean.guest_bedroom_delay_heat') }}"
            }
          block_4: "{{ states('input_boolean.guest_bedroom_block_4') }}"