blueprint:
  name: Control comfort settings
  description:  Control room's comfort settings. Enforce rules upon comfort settings.
  domain: automation
  author: Sebastian Sopola @ https://www.linkedin.com/in/sebastiansopola/
  input:
    comfort_settings: # Create input section to make input groups
      name: Provide min, max and target tmp
      icon: mdi:cog
      description: These inputs control the comfort settings for specific room in the heating system
      input:
        min_temperature:
          name: Input number min temperature
          selector: # declare rules of this input
            entity: # input must be entity in home assistant
              domain: input_number  # entity type of this entity
        max_temperature:
          name:  Input number max temperature
          selector:
            entity:
              domain: input_number
        target_temperature:
          name: Input number target temperature
          selector:
            entity:
              domain: input_number

mode: parallel # Multiple instances at once at run
max_exceeded: silent 

trigger_variables:
  min_temperature: !input min_temperature
  max_temperature: !input max_temperature
  target_temperature: !input target_temperature

trigger:
  - platform: state
    entity_id: !input min_temperature
    attribute: value
    id: min_temperature_ID

  - platform: state
    entity_id: !input max_temperature
    attribute: value
    id: max_temperature_ID

  - platform: state
    entity_id: !input target_temperature
    attribute: value
    id: target_temperature_ID

action:
  - service: input_number.set_value
    target: 
      entity_id: !input min_temperature
    data: 
      value: >
        {% if min_temperature > max_temperature %}
          {{ max_temperature }}
        {% else %}
          {{ min_temperature }}
        {% endif %}

  - service: input_number.set_value
    target:
      entity_id: !input max_temperature
    data:
      value: >
        {% if max_temperature < min_temperature %}
          {{ min_temperature }}
        {% else %}
          {{ max_temperature }}
        {% endif %}

  - service: input_number.set_value
    target:
      entity_id: !input target_temperature
    data:
      value: >
        {% if target_temperature < min_temperature %}
          {{ min_temperature }}
        {% elif target_temperature > max_temperature %}
          {{ max_temperature }}
        {% else %}
          {{ target_temperature }}
        {% endif %}