# Name: financial_conditions.yaml
# Author: Sebastian Sopola @ https://www.linkedin.com/in/sebastiansopola/
# Description: This file containts the blueprint to provide logic to evaluate financial conditions



blueprint:
  name: Evaluate financial conditions
  description: Evaluate financial conditions. Output will be one of the following options; delay, preheat or agressive heat 
  domain: automation
  author: Sebastian Sopola @ https://www.linkedin.com/in/sebastiansopola/
  input:
    housekeep:
      name: House Keep Information
      icon: mdi:hoop-house
      description:  Inputs provide notifications services ot administrator
      input:
        user:
          name: Housekeeper's phone
          description: This user is administrator of heating system
          selector:
            entity:
              filter:
    financial_information:
      name: Financial Information
      icon: mdi:finance
      description: Inputs related to financial data and market price trends used for heating strategy decisions
      input:
        price_trend:
          name: Price Trend
          description: Entity representing the calculated price trend for the next 8 hours
          selector:
            entity:
              filter:
                domain: input_text
        current_year_average_price:
          name: Current year's average price
          description: Sensor that provides the current year's average electric stock market price
          selector:
            entity:
              filter:
                domain: sensor
        nordpool:
          name: Nordpool
          description: Sensor that represents real-time electric stock market price data
          selector: 
            entity: 
              filter: 
                domain: sensor
    room_information:
      name: Room information
      icon: mdi:database
      description: These inputs provide information to make financial and heating strategy decisions
      input:  
        room_name:
          name: Room Name
          description: The name of the room for which the process should be conducted
          selector:
            text:
        room_temperature:
          name: Room temperature sensor 
          selector:
            entity: 
              filter: 
                domain: sensor  
        min_temperature:
          name: Minimum allowed room temperature
          selector:
            entity:
              filter:
                domain: input_number
        max_temperature:
          name: Maximum allowed room temperature
          selector:
            entity:
              filter:
                domain: input_number
        heating_schedule_start_time:
          name: Heating schedule start time
          selector:
            entity: 
              filter:
                domain: input_datetime
        heating_schedule_end_time:
            name: Heating schedule end time
            selector:
              entity: 
                filter:
                  domain: input_datetime
    pipeline_settings:
      name: Room Heating System Interface
      description: This is a sensor configured with sensor attributes to control heating system program flow
      selector:
        entity:
          domain: sensor


mode: restart
max_exceeded: silent

variables:
  user: !input user
  price_trend: !input price_trend
  current_year_average_price: !input current_year_average_price
  nordpool: !input nordpool
  room_name: !input room_name
  room_temperature: !input room_temperature
  min_temperature: !input min_temperature
  max_temperature: !input max_temperature
  heating_schedule_start_time: !input heating_schedule_start_time
  heating_schedule_end_time: !input heating_schedule_end_time

trigger_variables:
  pipeline_settings: !input pipeline_settings

trigger:
  - platform: template
    value_template: >
      {% set case_1 = state_attr(pipeline_settings, 'block_2_case_1') %}
      {% set case_2 = state_attr(pipeline_settings, 'block_2_case_2') %}
      {% set case_3 = state_attr(pipeline_settings, 'block_2_case_3') %}

      {% if case_1 == 'on' or case_2 == 'on' or case_3 == 'on' %}
        true
      {% else %}
        false
      {% endif %}

action:

  - choose:
      # Heat is at max
      - conditions:
          - condition: template
            value_template: "{{ state_attr(pipeline_settings, 'block_2_case_1') == 'on' }}"
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: >
                {{ 'input_boolean.' + room_name | lower + '_delay_heat' }}

      # Heat at min or below
      - conditions:
          - condition: template
            value_template: "{{ state_attr(pipeline_settings, 'block_2_case_2') == 'on' }}"
        sequence:
          - choose:
              - conditions:
                  # Price is expensive and heating is necessary
                  - condition: template
                    value_template: "{{ state_attr(nordpool, 'current_price') | float > states(current_year_average_price) | float }}"
                    #value_template: "{{ 15 | float > states(current_year_average_price) | float }}"
                sequence:
                  - service: notify.{{ user }}
                    data:
                      title: >
                        Huom! Korkea sähkön hinta
                      message: >
                        Hinta: {{ state_attr(nordpool, 'current_price') }} {{ state_attr(nordpool, 'unit_of_measurement') }}. 
                        Huone {{ room_name }} on {{ states(room_temperature) }}°C. 
                        Laske lämmitysrajaa? Nykyinen minimi: {{ states(min_temperature) }}°C. 
                        Reagoi 5 minuutin sisällä.
                  - delay: "00:05:00"  # 5 minutes
                  - choose:
                      - conditions:
                          # User updated minimum temperature
                          - condition: template
                            value_template: "{{ states(min_temperature) | float < states(room_temperature) | float }}"
                        sequence:
                          - service: input_boolean.turn_on
                            target:
                              entity_id: >
                                {{ 'input_boolean.' + room_name | lower + '_delay_heat' }}
                      - conditions:
                          # No user action, maintain heat at minimum
                          - condition: template
                            value_template: "{{ states(min_temperature) | float >= states(room_temperature) | float }}"
                        sequence:
                          - service: input_boolean.turn_on
                            target:
                              entity_id: >
                                {{ 'input_boolean.' + room_name | lower + '_maintain_heat' }}




              # Heat is needed and price is low
              - conditions:
                  - condition: template
                    value_template: "{{ state_attr(nordpool, 'current_price') < states(current_year_average_price) | float }}"
                sequence:
                  - service: system_log.write
                    data:
                      message: >
                        Price: {{ state_attr(nordpool, 'current_price') }}
                  - variables: 
                      cost_ratio: >
                        {{ ((states(current_year_average_price) | float - state_attr(nordpool, 'current_price') | float) / states(current_year_average_price) | float) * 100 }}

                  - choose:
                      # Price is more than 20% cheaper
                      - conditions:
                          - condition: template
                            value_template: "{{ cost_ratio >= 20 }}"
                        sequence:
                          - service: input_boolean.turn_on
                            target:
                              entity_id: >
                                {{ 'input_boolean.' + room_name | lower + '_preheat_max' }}

                      # Price is between 12%  to 20% cheaper
                      - conditions:
                          - condition: template
                            value_template: "{{ cost_ratio >= 12 and cost_ratio <= 20 }}"
                        sequence:
                          - service: input_boolean.turn_on
                            target:
                              entity_id: >
                                {{ 'input_boolean.' + room_name | lower + '_preheat_by_12' }}

                      # Price is 5% or more but less than 12% cheaper
                      - conditions:
                          - condition: template
                            value_template: "{{ cost_ratio >= 5 and cost_ratio < 12 }}"
                        sequence:
                          - service: input_boolean.turn_on
                            target:
                              entity_id: >
                                {{ 'input_boolean.' + room_name | lower + '_preheat_by_5' }}

                      # Price is less than 5% cheaper, fallback to minimum heating
                      - conditions:
                          - condition: template
                            value_template: "{{ cost_ratio < 5 }}"
                        sequence:
                          - service: input_boolean.turn_on
                            target:
                              entity_id: >
                                {{ 'input_boolean.' + room_name | lower + '_maintain_heat' }}

              # Heat is needed and price is average
              - conditions:
                  - condition: template
                    value_template: "{{ state_attr(nordpool, 'current_price') == states(current_year_average_price) | float }}"
                sequence:
                  - service: input_boolean.turn_on
                    target:
                      entity_id: >
                        {{ 'input_boolean.' + room_name | lower + '_maintain_heat' }}


      # Heat between min and max
      - conditions:
          - condition: template
            value_template: "{{ state_attr(pipeline_settings, 'block_2_case_3') == 'on' }}"
        sequence:
          # Define actions for this condition here


  # Debug: provide updated JSON 
               