# Name: room_conditions.yaml
# Author: Sebastian Sopola @ https://www.linkedin.com/in/sebastiansopola/
# Description: This file containts the blueprint to provide logic to evaluate room conditions



blueprint:
  name: Evaluate room conditions
  description: Evaluate room conditions. Output will be true to one of the options; heating_required, no_heating or withing_range
  domain: automation
  author: Sebastian Sopola @ https://www.linkedin.com/in/sebastiansopola/
  input:
    room_name:
      name: Room Name
      description: The name of the room for which the process should be conducted
      selector:
        text:
    room_conditions:
      name: Provide room_temperature, min_temperature and max_temperature
      icon: mdi:magnify
      description: These inputs allow to evaluate room conditions
      input:  
        room_temperature:
          name: Input sensor room temperature 
          selector: # declare rules of this input
            entity: # input must be entity in home assistant
              filter: # filter to allow only types described below
                domain: sensor  
        min_temperature:
          name: Input number min temperature
          selector:
            entity:
              filter:
                domain: input_number
        max_temperature:
          name: Input number max temperature
          selector:
            entity:
              filter:
                domain: input_number
    pipeline_settings:
      name: Room Heating System Interface
      description: This is a sensor configured with sensor attributes to control heating system program flow
      selector:
        entity:
          domain: sensor

mode: restart
max_exceeded: silent

variables:
  room_name: !input room_name
  room_temperature: !input room_temperature
  min_temperature: !input min_temperature
  max_temperature: !input max_temperature

trigger_variables:
  pipeline_settings: !input pipeline_settings

trigger:
  - platform: template
    value_template: >
      {% set state = state_attr(pipeline_settings, 'block_1') %}
      {% if state not in ['unknown', 'undefined', '', None] %}
        {{ state }}
      {% else %}
        false
      {% endif %}

action:

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ states(room_temperature) >= states(max_temperature) }}"
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: >
                {{ 'input_boolean.' + room_name | lower + '_block_2_case_1' }}
      - conditions:
          - condition: template
            value_template: "{{ states(room_temperature) | float <= states(min_temperature) | float }}"
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: >
                {{ 'input_boolean.' + room_name | lower + '_block_2_case_2' }}
      - conditions:
          - condition: template
            value_template: "{{ states(room_temperature) < states(max_temperature) and states(room_temperature) > states(min_temperature) }}"
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: >
                {{ 'input_boolean.' + room_name | lower + '_block_2_case_3' }}