# Name: start_process.yaml
# Author: Sebastian Sopola @ https://www.linkedin.com/in/sebastiansopola/
# Description: This file containts the blueprint to start process which evaluates rooms conditions, financial conditions, heating strategy and performs actions if needed



blueprint:
  name: Start heating process
  description: Start process which evaluates rooms conditions, financial conditions, heating strategy and performs actions if needed
  domain: automation
  input:
    room_name:
      name: Room Name
      description: The name of the room for which the process should be conducted
      selector:
        text:
    room_system_interface:
      name: Room System Interface
      description: This is a sensor configured with sensor attributes to control heating system program flow
      selector:
        entity:
          domain: sensor

variables:
  room_name: !input room_name
  room_system_interface: !input room_system_interface

trigger:
  - platform: time_pattern
    minutes: 0  # Trigger at the start of every hour

# Test functionality and configuration with these lines
#trigger:
#  - platform: time_pattern
#    seconds: "/1"  # Trigger every second

action:

  - service: input_boolean.turn_on
    target:
      entity_id: >
        {{ 'input_boolean.' + room_name | lower + '_block_0' }}